{
 "title": "Veeam Office 365 Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> keep(columns: [\"veeamjobname\"])\n  |> group(columns: [\"veeamjobname\"])"
   },
   {
    "name": "Repository",
    "label": "Repository",
    "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_repository\")\n  |> keep(columns: [\"repository\"])\n  |> distinct(column: \"repository\")\n  |> group()"
   },
   {
    "name": "Organization",
    "label": "Organization",
    "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_organization\")\n  |> keep(columns: [\"veeamOrgName\"])\n  |> distinct(column: \"veeamOrgName\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Veeam Version",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_version\")\n  |> keep(columns: [\"veeamVersion\"])\n  |> distinct(column: \"veeamVersion\")"
      }
     ]
    },
    {
     "title": "Total Threads Number",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_proxies\")\n  |> filter(fn: (r) => r[\"_field\"] == \"threadsNumber\")\n  |> last ()"
      }
     ]
    }
   ]
  },
  { "title": "Job Status Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$JobName",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "repeat": "JobName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${JobName:regex}/)\n  |> group()\n  |> aggregateWindow(every: 24h, fn: min)\n"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${JobName:regex}/)\n  |> group(columns: [\"veeamjobname\"])\n  |> aggregateWindow(every: 24h, fn: min, timeSrc: \"_time\", timeDst: \"_time\", createEmpty: false)"
    }
   ]
  },
  {
   "title": "The Duration Of The Last Job Run",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "$JobName",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
     "repeat": "JobName",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalDuration\")\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${JobName:regex}/ )\n  |> group(columns: [\"veeamjobname\"])\n  |> last ()"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Processing Rate/Transferred Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$JobName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "repeat": "JobName",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"processingRate\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${JobName:regex}/)\r\n  |> group ()"
      },
      {
       "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"transferredData\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${JobName:regex}/)\r\n  |> group ()"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs Read/Write Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "$JobName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "repeat": "JobName",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"readRate\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${JobName:regex}/)\r\n  |> group ()"
      },
      {
       "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_jobs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"writeRate\")\r\n  |> filter(fn: (r) => r[\"veeamjobname\"] =~ /${JobName:regex}/)\r\n  |> group ()"
      }
     ]
    }
   ]
  },
  {
   "title": "User Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Licensed Users $Organization",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_organization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"licensedUsers\")\n  |> filter(fn: (r) => r[\"veeamOrgName\"] =~ /${Organization:regex}/)\n  |> last ()"
      }
     ]
    },
    {
     "title": "New User $Organization",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_organization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"newUsers\")\n  |> filter(fn: (r) => r[\"veeamOrgName\"] =~ /${Organization:regex}/)\n  |> last ()"
      }
     ]
    },
    {
     "title": "Licensed User",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_overview_OD\")\n  |> filter(fn: (r) => r[\"_field\"] == \"licensedUser\")\n  |> filter(fn: (r) => r[\"veeamOrgName\"] =~ /${Organization:regex}/)\n  |> distinct(column: \"veeamUserName\")\n  |> keep(columns: [\"_value\"])\n  |> group()\n"
      }
     ]
    },
    {
     "title": "Protected User",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_overview_OD\")\n  |> filter(fn: (r) => r[\"_field\"] == \"protectedUser\")\n  |> filter(fn: (r) => r[\"veeamOrgName\"] =~ /${Organization:regex}/)\n  |> distinct(column: \"veeamUserName\")\n  |> keep(columns: [\"_value\"])\n  |> group()\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Repository Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Repository",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "repeat": "Repository",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_repository\" or r[\"_measurement\"] == \"veeam_vbr_repositories\")\r\n  |> filter(fn: (r) => r[\"repository\"] =~ /${Repository:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"freeSpace\")\r\n    |> last(column: \"_value\")"
      },
      {
       "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_repository\")\r\n  |> filter(fn: (r) => r[\"repository\"] =~ /${Repository:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity\" or r[\"_field\"] == \"freeSpace\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      difference: r.capacity - r.freeSpace\r\n    }))\r\n  |> last(column: \"difference\")\r\n  |> keep(columns: [\"difference\"])"
      },
      {
       "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_office365_repository\")\r\n  |> filter(fn: (r) => r[\"repository\"] =~ /${Repository:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity\")\r\n  |> last(column: \"_value\")"
      }
     ]
    },
    {
     "title": "$Repository",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
     "repeat": "Repository",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"veeam\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"repository\"] =~ /${Repository:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity\" or r[\"_field\"] == \"freeSpace\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: (float(v: r.capacity) - float(v: r.freeSpace)) * (100.0 /float(v: r.capacity)) }))\r\n  |> last(column: \"_value\")\r\n  |> keep(columns: [\"_value\"])"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<div style=\"text-align: right;\">\n    <a href=\"https://furycode.org/\">\n        <img src=\"https://furycode.org/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fflame.26b9b203.png&w=640&q=75\" height=\"80\" alt=\"Flame\">\n    </a>\n</div>\n"
   }
  }
 ]
}