{
 "title": "Veeam Backup Overview",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_vbr_sessions\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"veeamVBRSessionJobName\"])\n  |> distinct(column: \"veeamVBRSessionJobName\")\n  |> group()"
   },
   {
    "name": "Repository",
    "label": "Repository",
    "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_vbr_repositories\")\n  |> filter(fn: (r) => r[\"_field\"] == \"veeamVBRRepoUsed\")\n  |> keep(columns: [\"veeamVBRRepoName\"])\n  |> distinct(column: \"veeamVBRRepoName\")\n  |> group()"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Veeam Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_vbr_info\")\n  |> keep(columns: [\"veeamVBRVersion\"])\n  |> distinct(column: \"veeamVBRVersion\")"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_vbr_managedservers\")\n  |> filter(fn: (r) => r[\"_field\"] == \"veeamVBRMSInternalID\")\n  |> group(columns: [\"veeamVBRMSName\"])\n  |> last()"
    }
   ]
  },
  { "title": "Job Status Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$JobName",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "repeat": "JobName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_vbr_sessions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"veeamSessionJobResult\")\n  |> filter(fn: (r) => r[\"veeamVBRSessionJobName\"] =~ /${JobName:regex}/ )\n  |> group()\n  |> aggregateWindow(every: 24h, fn: min)\n"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"veeam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"veeam_vbr_sessions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"veeamSessionJobResult\")\n  |> filter(fn: (r) => r[\"veeamVBRSessionJobName\"] =~ /${JobName:regex}/ )\n  |> group(columns: [\"veeamVBRSessionJobName\"])\n  |> aggregateWindow(every: 24h, fn: min, timeSrc: \"_time\", timeDst: \"_time\", createEmpty: false)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 },
   "options": {
    "content": "<div style=\"text-align: right;\">\n    <a href=\"https://furycode.org/\">\n        <img src=\"https://furycode.org/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fflame.26b9b203.png&w=640&q=75\" height=\"80\" alt=\"Flame\">\n    </a>\n</div>\n"
   }
  }
 ]
}