name: Build and deploy

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened]

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGION: "europe-west6"
  PROJECT: "fury-code"
  ARTIFACT_REPO: "public"
  SERVICE_NAME: "veeam-metrics-collector"

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push:
    name: Build container image and push
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.SA_EMAIL }}"
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: "${{ env.REGION }}-docker.pkg.dev"
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
          # For the main branch
          echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/pull/* ]]; then
          # For pull requests, use the branch name from the event payload
          sanitized_ref=$(echo "${GITHUB_HEAD_REF}" | tr '/' '-')
          echo "tag=${sanitized_ref}" >> $GITHUB_OUTPUT
          else
          # For other branches
          sanitized_ref=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          echo "tag=${sanitized_ref}" >> $GITHUB_OUTPUT
          fi

      - name: Print tag
        run: |
          echo "The generated branch tag is: ${{ steps.get-tag.outputs.tag }}"

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
             ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${{ steps.get-tag.outputs.tag }}

